package com.lwp.model;

public enum Pages {
	COMPANY_OVERVIEW,
	MANGEMENT,
	VISION_MISSION,
	CORE_VALUES,
	SUSTAINABILITY,
	AIR_FREIGHT,
	OCAN_FREIGHT,
	CUSTOME_CLEARANCE,
	PROJECT_SOLUTION_MANAGEMENT,
	PROJECT_TRANSPORT_MANAGEMENT,
	CONSULTING_IMPL
}
